# ===============================
# = Data Source Configuration  =
# ===============================
spring.datasource.url=jdbc:postgresql://PC-SEC-VILA:5433/easy_pdv_db
spring.datasource.username=user
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.time_zone=UTC