# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/easy_pdv_db
spring.datasource.username=user
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# Logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

